// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventKind.proto

#ifndef PROTOBUF_eventKind_2eproto__INCLUDED
#define PROTOBUF_eventKind_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_eventKind_2eproto();
void protobuf_AssignDesc_eventKind_2eproto();
void protobuf_ShutdownFile_eventKind_2eproto();

class chalkBoard;

// ===================================================================

class chalkBoard : public ::google::protobuf::Message {
 public:
  chalkBoard();
  virtual ~chalkBoard();

  chalkBoard(const chalkBoard& from);

  inline chalkBoard& operator=(const chalkBoard& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const chalkBoard& default_instance();

  void Swap(chalkBoard* other);

  // implements Message ----------------------------------------------

  chalkBoard* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const chalkBoard& from);
  void MergeFrom(const chalkBoard& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string changes = 1 [default = ""];
  inline bool has_changes() const;
  inline void clear_changes();
  static const int kChangesFieldNumber = 1;
  inline const ::std::string& changes() const;
  inline void set_changes(const ::std::string& value);
  inline void set_changes(const char* value);
  inline void set_changes(const char* value, size_t size);
  inline ::std::string* mutable_changes();
  inline ::std::string* release_changes();
  inline void set_allocated_changes(::std::string* changes);

  // optional int32 where = 2 [default = 0];
  inline bool has_where() const;
  inline void clear_where();
  static const int kWhereFieldNumber = 2;
  inline ::google::protobuf::int32 where() const;
  inline void set_where(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:chalkBoard)
 private:
  inline void set_has_changes();
  inline void clear_has_changes();
  inline void set_has_where();
  inline void clear_has_where();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* changes_;
  ::google::protobuf::int32 where_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_eventKind_2eproto();
  friend void protobuf_AssignDesc_eventKind_2eproto();
  friend void protobuf_ShutdownFile_eventKind_2eproto();

  void InitAsDefaultInstance();
  static chalkBoard* default_instance_;
};
// ===================================================================


// ===================================================================

// chalkBoard

// optional string changes = 1 [default = ""];
inline bool chalkBoard::has_changes() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void chalkBoard::set_has_changes() {
  _has_bits_[0] |= 0x00000001u;
}
inline void chalkBoard::clear_has_changes() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void chalkBoard::clear_changes() {
  if (changes_ != &::google::protobuf::internal::kEmptyString) {
    changes_->clear();
  }
  clear_has_changes();
}
inline const ::std::string& chalkBoard::changes() const {
  return *changes_;
}
inline void chalkBoard::set_changes(const ::std::string& value) {
  set_has_changes();
  if (changes_ == &::google::protobuf::internal::kEmptyString) {
    changes_ = new ::std::string;
  }
  changes_->assign(value);
}
inline void chalkBoard::set_changes(const char* value) {
  set_has_changes();
  if (changes_ == &::google::protobuf::internal::kEmptyString) {
    changes_ = new ::std::string;
  }
  changes_->assign(value);
}
inline void chalkBoard::set_changes(const char* value, size_t size) {
  set_has_changes();
  if (changes_ == &::google::protobuf::internal::kEmptyString) {
    changes_ = new ::std::string;
  }
  changes_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* chalkBoard::mutable_changes() {
  set_has_changes();
  if (changes_ == &::google::protobuf::internal::kEmptyString) {
    changes_ = new ::std::string;
  }
  return changes_;
}
inline ::std::string* chalkBoard::release_changes() {
  clear_has_changes();
  if (changes_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = changes_;
    changes_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void chalkBoard::set_allocated_changes(::std::string* changes) {
  if (changes_ != &::google::protobuf::internal::kEmptyString) {
    delete changes_;
  }
  if (changes) {
    set_has_changes();
    changes_ = changes;
  } else {
    clear_has_changes();
    changes_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 where = 2 [default = 0];
inline bool chalkBoard::has_where() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void chalkBoard::set_has_where() {
  _has_bits_[0] |= 0x00000002u;
}
inline void chalkBoard::clear_has_where() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void chalkBoard::clear_where() {
  where_ = 0;
  clear_has_where();
}
inline ::google::protobuf::int32 chalkBoard::where() const {
  return where_;
}
inline void chalkBoard::set_where(::google::protobuf::int32 value) {
  set_has_where();
  where_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_eventKind_2eproto__INCLUDED
