// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventKind.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "eventKind.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* chalkBoard_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  chalkBoard_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_eventKind_2eproto() {
  protobuf_AddDesc_eventKind_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "eventKind.proto");
  GOOGLE_CHECK(file != NULL);
  chalkBoard_descriptor_ = file->message_type(0);
  static const int chalkBoard_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(chalkBoard, changes_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(chalkBoard, where_),
  };
  chalkBoard_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      chalkBoard_descriptor_,
      chalkBoard::default_instance_,
      chalkBoard_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(chalkBoard, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(chalkBoard, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(chalkBoard));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_eventKind_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    chalkBoard_descriptor_, &chalkBoard::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_eventKind_2eproto() {
  delete chalkBoard::default_instance_;
  delete chalkBoard_reflection_;
}

void protobuf_AddDesc_eventKind_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017eventKind.proto\"1\n\nchalkBoard\022\021\n\007chang"
    "es\030\001 \001(\t:\000\022\020\n\005where\030\002 \001(\005:\0010", 68);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "eventKind.proto", &protobuf_RegisterTypes);
  chalkBoard::default_instance_ = new chalkBoard();
  chalkBoard::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_eventKind_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_eventKind_2eproto {
  StaticDescriptorInitializer_eventKind_2eproto() {
    protobuf_AddDesc_eventKind_2eproto();
  }
} static_descriptor_initializer_eventKind_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int chalkBoard::kChangesFieldNumber;
const int chalkBoard::kWhereFieldNumber;
#endif  // !_MSC_VER

chalkBoard::chalkBoard()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void chalkBoard::InitAsDefaultInstance() {
}

chalkBoard::chalkBoard(const chalkBoard& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void chalkBoard::SharedCtor() {
  _cached_size_ = 0;
  changes_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  where_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

chalkBoard::~chalkBoard() {
  SharedDtor();
}

void chalkBoard::SharedDtor() {
  if (changes_ != &::google::protobuf::internal::kEmptyString) {
    delete changes_;
  }
  if (this != default_instance_) {
  }
}

void chalkBoard::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* chalkBoard::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return chalkBoard_descriptor_;
}

const chalkBoard& chalkBoard::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_eventKind_2eproto();
  return *default_instance_;
}

chalkBoard* chalkBoard::default_instance_ = NULL;

chalkBoard* chalkBoard::New() const {
  return new chalkBoard;
}

void chalkBoard::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_changes()) {
      if (changes_ != &::google::protobuf::internal::kEmptyString) {
        changes_->clear();
      }
    }
    where_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool chalkBoard::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string changes = 1 [default = ""];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_changes()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->changes().data(), this->changes().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_where;
        break;
      }

      // optional int32 where = 2 [default = 0];
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_where:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &where_)));
          set_has_where();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void chalkBoard::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string changes = 1 [default = ""];
  if (has_changes()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->changes().data(), this->changes().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->changes(), output);
  }

  // optional int32 where = 2 [default = 0];
  if (has_where()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->where(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* chalkBoard::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string changes = 1 [default = ""];
  if (has_changes()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->changes().data(), this->changes().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->changes(), target);
  }

  // optional int32 where = 2 [default = 0];
  if (has_where()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->where(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int chalkBoard::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string changes = 1 [default = ""];
    if (has_changes()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->changes());
    }

    // optional int32 where = 2 [default = 0];
    if (has_where()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->where());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void chalkBoard::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const chalkBoard* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const chalkBoard*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void chalkBoard::MergeFrom(const chalkBoard& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_changes()) {
      set_changes(from.changes());
    }
    if (from.has_where()) {
      set_where(from.where());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void chalkBoard::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void chalkBoard::CopyFrom(const chalkBoard& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool chalkBoard::IsInitialized() const {

  return true;
}

void chalkBoard::Swap(chalkBoard* other) {
  if (other != this) {
    std::swap(changes_, other->changes_);
    std::swap(where_, other->where_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata chalkBoard::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = chalkBoard_descriptor_;
  metadata.reflection = chalkBoard_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
